version: 2.1
jobs:
  node:
    working_directory: ~/demo-react-native
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

    
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

  
      - persist_to_workspace:
          root: ~/demo-react-native
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

 
            
  android-build-and-test:
    working_directory: ~/demo-react-native
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/demo-react-native
          
      - attach_workspace:
          at: ~/demo-react-native

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}   

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules      

      - run:
          name: chmod permissions
          
          command: |
           cd android &&  chmod +x ./gradlew

      - run:
          name: Assemble release build
          command: |
            find .
            cd android && ./gradlew bundleRelease
            find .
      - store_artifacts:
        
          path: android/app/build/outputs/bundle/release

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - run: apk update
      - run: apk upgrade
      - run: apk --no-cache add --update openssh git curl
      - checkout
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          sonar-scanner -D \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sourceEncoding=UTF-8 \ 
            -Dsonar.sources="."

workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
      - sonarqube

     
