version: 2.1
jobs:
  node:
    working_directory: ~/demo-react-native
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

   

      - persist_to_workspace:
          root: ~/demo-react-native
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

 
            
  android-build-and-test:
    working_directory: ~/demo-react-native/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
        
      - attach_workspace:
          at: ~/demo-react-native

      - run:
          name: Assemble release build
          command: |
            cd /android &&
            ./gradlew bundleRelease
      - store_artifacts:
          path: app/build/outputs/bundle/release 

workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
     